catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
  vite-plus: 0.3.2
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.3.2"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.3.2"
  - "@voidzero-dev/vite-plus-darwin-x64@0.3.2"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.2"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.3.2"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.3.2"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.3.2"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.2"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.3.2"
  - vite-plus@0.3.2
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
